// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by MimironsGoldOMatic.ApiTsGen.
import axios, { type AxiosInstance } from 'axios'
import type {
  ConfirmAcceptanceRequest,
  CreatePayoutRequest,
  E2ePreparePendingRequest,
  E2ePreparePendingResponse,
  PatchPayoutStatusRequest,
  PayoutDto,
  PoolMeResponse,
  RouletteStateResponse,
  VerifyCandidateRequest,
  VersionInfoDto,
} from './models'

export class MimironsGoldOMaticApiClient {
  private readonly client: AxiosInstance

  public constructor(
    baseUrl: string,
    tokenProvider: () => string | null,
    axiosInstance?: AxiosInstance,
  ) {
    this.client = axiosInstance ?? axios.create({
      baseURL: baseUrl.replace(/\/$/, ''),
      headers: {
        'Content-Type': 'application/json',
      },
    })

    this.client.interceptors.request.use((config) => {
      const token = tokenProvider()
      if (token) {
        config.headers.Authorization = `Bearer ${token}`
      }
      return config
    })
  }

  public async getPayoutsMyLast(signal?: AbortSignal): Promise<PayoutDto> {
    const { data } = await this.client.get<PayoutDto>('/api/payouts/my-last', { signal })
    return data
  }

  public async getPayoutsPending(signal?: AbortSignal): Promise<PayoutDto[]> {
    const { data } = await this.client.get<PayoutDto[]>('/api/payouts/pending', { signal })
    return data
  }

  public async getPoolMe(signal?: AbortSignal): Promise<PoolMeResponse> {
    const { data } = await this.client.get<PoolMeResponse>('/api/pool/me', { signal })
    return data
  }

  public async getRouletteState(signal?: AbortSignal): Promise<RouletteStateResponse> {
    const { data } = await this.client.get<RouletteStateResponse>('/api/roulette/state', { signal })
    return data
  }

  public async getVersion(signal?: AbortSignal): Promise<VersionInfoDto> {
    const { data } = await this.client.get<VersionInfoDto>('/api/version', { signal })
    return data
  }

  public async patchPayoutsIdGuidStatus(id: string, request: PatchPayoutStatusRequest, signal?: AbortSignal): Promise<PayoutDto> {
    const { data } = await this.client.patch<PayoutDto>(`/api/payouts/${id}/status`, request, { signal })
    return data
  }

  public async postE2ePreparePendingPayout(request: E2ePreparePendingRequest, signal?: AbortSignal): Promise<E2ePreparePendingResponse> {
    const { data } = await this.client.post<E2ePreparePendingResponse>('/api/e2e/prepare-pending-payout', request, { signal })
    return data
  }

  public async postPayoutsClaim(request: CreatePayoutRequest, signal?: AbortSignal): Promise<PayoutDto> {
    const { data } = await this.client.post<PayoutDto>('/api/payouts/claim', request, { signal })
    return data
  }

  public async postPayoutsIdGuidConfirmAcceptance(id: string, request: ConfirmAcceptanceRequest, signal?: AbortSignal): Promise<void> {
    await this.client.post(`/api/payouts/${id}/confirm-acceptance`, request, { signal })
  }

  public async postRouletteVerifyCandidate(request: VerifyCandidateRequest, signal?: AbortSignal): Promise<void> {
    await this.client.post('/api/roulette/verify-candidate', request, { signal })
  }

  public async postTwitchEventsub(signal?: AbortSignal): Promise<void> {
    await this.client.post('/api/twitch/eventsub', undefined, { signal })
  }

}
