// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by src/Tools/MimironsGoldOMatic.ApiTsGen.
// Any manual changes will be overwritten by the next generation run.

export interface ConfirmAcceptanceRequest {
  characterName: string
}

export interface ConfirmGiftRequest {
  confirmed: boolean
}

export interface CreateGiftRequest {
  streamerId: string
  characterName: string
}

export interface CreatePayoutRequest {
  characterName: string
  enrollmentRequestId: string
}

export interface E2ePreparePendingRequest {
  twitchUserId: string
}

export interface E2ePreparePendingResponse {
  payoutId: string
  characterName: string
}

export type GiftRequestState =
  | 'Pending'
  | 'SelectingItem'
  | 'ItemSelected'
  | 'WaitingConfirmation'
  | 'Completed'
  | 'Failed';

export interface GiftSelectedItemDto {
  name: string
  id: number
  count: number
  link: string
  texture: string
  bagId: number
  slotId: number
}

export interface PatchGiftRequestState {
  state: GiftRequestState
  reason: string | null
}

export interface PatchPayoutStatusRequest {
  status: PayoutStatus
}

export interface PayoutDto {
  id: string
  twitchUserId: string
  twitchDisplayName: string
  characterName: string
  goldAmount: number
  enrollmentRequestId: string
  status: PayoutStatus
  createdAt: string
  isRewardSentAnnouncedToChat: boolean
}

export type PayoutStatus =
  | 'Pending'
  | 'InProgress'
  | 'Sent'
  | 'Failed'
  | 'Cancelled'
  | 'Expired';

export interface PoolMeResponse {
  isEnrolled: boolean
  characterName: string | null
}

export interface RouletteStateResponse {
  nextSpinAt: string
  serverNow: string
  spinIntervalSeconds: number
  poolParticipantCount: number
  spinPhase: string
  currentSpinCycleId: string | null
}

export interface SelectGiftItemRequest {
  item: GiftSelectedItemDto
}

export interface VerifyCandidateRequest {
  schemaVersion: number
  spinCycleId: string
  characterName: string
  online: boolean
  capturedAt: string
}

export interface VersionInfoDto {
  version: string
  releaseNotesUrl: string | null
  minimumDesktopVersion: string | null
  minimumAddonVersion: string | null
  minimumExtensionVersion: string | null
}

