version: "3"

services:
    mgmdb:
        environment:
            - POSTGRES_DB=mgm
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        image: postgres:16-alpine
        hostname: mgmdb
        expose:
            - 5432
        ports:
            - 5432:5432
        container_name: mgmdb
        labels:
            - SERVICE_NAME=mgmdb
        volumes:
            - postgres:/var/lib/postgresql/data

volumes:
    postgres: